# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prystine_detection/prystine/protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from prystine_detection.prystine.protos import prystine_pb2 as prystine__detection_dot_prystine_dot_protos_dot_prystine__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='prystine_detection/prystine/protos/model.proto',
  package='prystine_detection.prystine.protos',
  syntax='proto3',
  serialized_pb=_b('\n.prystine_detection/prystine/protos/model.proto\x12\"prystine_detection.prystine.protos\x1a\x31prystine_detection/prystine/protos/prystine.proto\"Y\n\x0e\x44\x65tectionModel\x12>\n\x06second\x18\x01 \x01(\x0b\x32,.prystine_detection.prystine.protos.VoxelNetH\x00\x42\x07\n\x05modelb\x06proto3')
  ,
  dependencies=[prystine__detection_dot_prystine_dot_protos_dot_prystine__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETECTIONMODEL = _descriptor.Descriptor(
  name='DetectionModel',
  full_name='prystine_detection.prystine.protos.DetectionModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='second', full_name='prystine_detection.prystine.protos.DetectionModel.second', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='model', full_name='prystine_detection.prystine.protos.DetectionModel.model',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=137,
  serialized_end=226,
)

_DETECTIONMODEL.fields_by_name['second'].message_type = prystine__detection_dot_prystine_dot_protos_dot_prystine__pb2._VOXELNET
_DETECTIONMODEL.oneofs_by_name['model'].fields.append(
  _DETECTIONMODEL.fields_by_name['second'])
_DETECTIONMODEL.fields_by_name['second'].containing_oneof = _DETECTIONMODEL.oneofs_by_name['model']
DESCRIPTOR.message_types_by_name['DetectionModel'] = _DETECTIONMODEL

DetectionModel = _reflection.GeneratedProtocolMessageType('DetectionModel', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONMODEL,
  __module__ = 'prystine_detection.prystine.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.DetectionModel)
  ))
_sym_db.RegisterMessage(DetectionModel)


# @@protoc_insertion_point(module_scope)
