# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prystine_detection/prystine/protos/preprocess.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prystine_detection/prystine/protos/preprocess.proto',
  package='prystine_detection.prystine.protos',
  syntax='proto3',
  serialized_pb=_b('\n3prystine_detection/prystine/protos/preprocess.proto\x12\"prystine_detection.prystine.protos\"\x80\x02\n\x19\x44\x61tabasePreprocessingStep\x12X\n\x14\x66ilter_by_difficulty\x18\x01 \x01(\x0b\x32\x38.prystine_detection.prystine.protos.DBFilterByDifficultyH\x00\x12j\n\x18\x66ilter_by_min_num_points\x18\x02 \x01(\x0b\x32\x46.prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruthH\x00\x42\x1d\n\x1b\x64\x61tabase_preprocessing_step\"4\n\x14\x44\x42\x46ilterByDifficulty\x12\x1c\n\x14removed_difficulties\x18\x01 \x03(\x05\"\xd8\x01\n\"DBFilterByMinNumPointInGroundTruth\x12y\n\x13min_num_point_pairs\x18\x01 \x03(\x0b\x32\\.prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth.MinNumPointPairsEntry\x1a\x37\n\x15MinNumPointPairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATABASEPREPROCESSINGSTEP = _descriptor.Descriptor(
  name='DatabasePreprocessingStep',
  full_name='prystine_detection.prystine.protos.DatabasePreprocessingStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_by_difficulty', full_name='prystine_detection.prystine.protos.DatabasePreprocessingStep.filter_by_difficulty', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_by_min_num_points', full_name='prystine_detection.prystine.protos.DatabasePreprocessingStep.filter_by_min_num_points', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='database_preprocessing_step', full_name='prystine_detection.prystine.protos.DatabasePreprocessingStep.database_preprocessing_step',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=92,
  serialized_end=348,
)


_DBFILTERBYDIFFICULTY = _descriptor.Descriptor(
  name='DBFilterByDifficulty',
  full_name='prystine_detection.prystine.protos.DBFilterByDifficulty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='removed_difficulties', full_name='prystine_detection.prystine.protos.DBFilterByDifficulty.removed_difficulties', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=402,
)


_DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY = _descriptor.Descriptor(
  name='MinNumPointPairsEntry',
  full_name='prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth.MinNumPointPairsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth.MinNumPointPairsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth.MinNumPointPairsEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=621,
)

_DBFILTERBYMINNUMPOINTINGROUNDTRUTH = _descriptor.Descriptor(
  name='DBFilterByMinNumPointInGroundTruth',
  full_name='prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_num_point_pairs', full_name='prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth.min_num_point_pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=621,
)

_DATABASEPREPROCESSINGSTEP.fields_by_name['filter_by_difficulty'].message_type = _DBFILTERBYDIFFICULTY
_DATABASEPREPROCESSINGSTEP.fields_by_name['filter_by_min_num_points'].message_type = _DBFILTERBYMINNUMPOINTINGROUNDTRUTH
_DATABASEPREPROCESSINGSTEP.oneofs_by_name['database_preprocessing_step'].fields.append(
  _DATABASEPREPROCESSINGSTEP.fields_by_name['filter_by_difficulty'])
_DATABASEPREPROCESSINGSTEP.fields_by_name['filter_by_difficulty'].containing_oneof = _DATABASEPREPROCESSINGSTEP.oneofs_by_name['database_preprocessing_step']
_DATABASEPREPROCESSINGSTEP.oneofs_by_name['database_preprocessing_step'].fields.append(
  _DATABASEPREPROCESSINGSTEP.fields_by_name['filter_by_min_num_points'])
_DATABASEPREPROCESSINGSTEP.fields_by_name['filter_by_min_num_points'].containing_oneof = _DATABASEPREPROCESSINGSTEP.oneofs_by_name['database_preprocessing_step']
_DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY.containing_type = _DBFILTERBYMINNUMPOINTINGROUNDTRUTH
_DBFILTERBYMINNUMPOINTINGROUNDTRUTH.fields_by_name['min_num_point_pairs'].message_type = _DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY
DESCRIPTOR.message_types_by_name['DatabasePreprocessingStep'] = _DATABASEPREPROCESSINGSTEP
DESCRIPTOR.message_types_by_name['DBFilterByDifficulty'] = _DBFILTERBYDIFFICULTY
DESCRIPTOR.message_types_by_name['DBFilterByMinNumPointInGroundTruth'] = _DBFILTERBYMINNUMPOINTINGROUNDTRUTH

DatabasePreprocessingStep = _reflection.GeneratedProtocolMessageType('DatabasePreprocessingStep', (_message.Message,), dict(
  DESCRIPTOR = _DATABASEPREPROCESSINGSTEP,
  __module__ = 'prystine_detection.prystine.protos.preprocess_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.DatabasePreprocessingStep)
  ))
_sym_db.RegisterMessage(DatabasePreprocessingStep)

DBFilterByDifficulty = _reflection.GeneratedProtocolMessageType('DBFilterByDifficulty', (_message.Message,), dict(
  DESCRIPTOR = _DBFILTERBYDIFFICULTY,
  __module__ = 'prystine_detection.prystine.protos.preprocess_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.DBFilterByDifficulty)
  ))
_sym_db.RegisterMessage(DBFilterByDifficulty)

DBFilterByMinNumPointInGroundTruth = _reflection.GeneratedProtocolMessageType('DBFilterByMinNumPointInGroundTruth', (_message.Message,), dict(

  MinNumPointPairsEntry = _reflection.GeneratedProtocolMessageType('MinNumPointPairsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY,
    __module__ = 'prystine_detection.prystine.protos.preprocess_pb2'
    # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth.MinNumPointPairsEntry)
    ))
  ,
  DESCRIPTOR = _DBFILTERBYMINNUMPOINTINGROUNDTRUTH,
  __module__ = 'prystine_detection.prystine.protos.preprocess_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.DBFilterByMinNumPointInGroundTruth)
  ))
_sym_db.RegisterMessage(DBFilterByMinNumPointInGroundTruth)
_sym_db.RegisterMessage(DBFilterByMinNumPointInGroundTruth.MinNumPointPairsEntry)


_DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY.has_options = True
_DBFILTERBYMINNUMPOINTINGROUNDTRUTH_MINNUMPOINTPAIRSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
