# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prystine_detection/prystine/protos/similarity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prystine_detection/prystine/protos/similarity.proto',
  package='prystine_detection.prystine.protos',
  syntax='proto3',
  serialized_pb=_b('\n3prystine_detection/prystine/protos/similarity.proto\x12\"prystine_detection.prystine.protos\"\xbe\x02\n\x1aRegionSimilarityCalculator\x12X\n\x15rotate_iou_similarity\x18\x01 \x01(\x0b\x32\x37.prystine_detection.prystine.protos.RotateIouSimilarityH\x00\x12Z\n\x16nearest_iou_similarity\x18\x02 \x01(\x0b\x32\x38.prystine_detection.prystine.protos.NearestIouSimilarityH\x00\x12U\n\x13\x64istance_similarity\x18\x03 \x01(\x0b\x32\x36.prystine_detection.prystine.protos.DistanceSimilarityH\x00\x42\x13\n\x11region_similarity\"\x15\n\x13RotateIouSimilarity\"\x16\n\x14NearestIouSimilarity\"Z\n\x12\x44istanceSimilarity\x12\x15\n\rdistance_norm\x18\x01 \x01(\x02\x12\x15\n\rwith_rotation\x18\x02 \x01(\x08\x12\x16\n\x0erotation_alpha\x18\x03 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REGIONSIMILARITYCALCULATOR = _descriptor.Descriptor(
  name='RegionSimilarityCalculator',
  full_name='prystine_detection.prystine.protos.RegionSimilarityCalculator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotate_iou_similarity', full_name='prystine_detection.prystine.protos.RegionSimilarityCalculator.rotate_iou_similarity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nearest_iou_similarity', full_name='prystine_detection.prystine.protos.RegionSimilarityCalculator.nearest_iou_similarity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance_similarity', full_name='prystine_detection.prystine.protos.RegionSimilarityCalculator.distance_similarity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='region_similarity', full_name='prystine_detection.prystine.protos.RegionSimilarityCalculator.region_similarity',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=92,
  serialized_end=410,
)


_ROTATEIOUSIMILARITY = _descriptor.Descriptor(
  name='RotateIouSimilarity',
  full_name='prystine_detection.prystine.protos.RotateIouSimilarity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=433,
)


_NEARESTIOUSIMILARITY = _descriptor.Descriptor(
  name='NearestIouSimilarity',
  full_name='prystine_detection.prystine.protos.NearestIouSimilarity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=457,
)


_DISTANCESIMILARITY = _descriptor.Descriptor(
  name='DistanceSimilarity',
  full_name='prystine_detection.prystine.protos.DistanceSimilarity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance_norm', full_name='prystine_detection.prystine.protos.DistanceSimilarity.distance_norm', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='with_rotation', full_name='prystine_detection.prystine.protos.DistanceSimilarity.with_rotation', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation_alpha', full_name='prystine_detection.prystine.protos.DistanceSimilarity.rotation_alpha', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=549,
)

_REGIONSIMILARITYCALCULATOR.fields_by_name['rotate_iou_similarity'].message_type = _ROTATEIOUSIMILARITY
_REGIONSIMILARITYCALCULATOR.fields_by_name['nearest_iou_similarity'].message_type = _NEARESTIOUSIMILARITY
_REGIONSIMILARITYCALCULATOR.fields_by_name['distance_similarity'].message_type = _DISTANCESIMILARITY
_REGIONSIMILARITYCALCULATOR.oneofs_by_name['region_similarity'].fields.append(
  _REGIONSIMILARITYCALCULATOR.fields_by_name['rotate_iou_similarity'])
_REGIONSIMILARITYCALCULATOR.fields_by_name['rotate_iou_similarity'].containing_oneof = _REGIONSIMILARITYCALCULATOR.oneofs_by_name['region_similarity']
_REGIONSIMILARITYCALCULATOR.oneofs_by_name['region_similarity'].fields.append(
  _REGIONSIMILARITYCALCULATOR.fields_by_name['nearest_iou_similarity'])
_REGIONSIMILARITYCALCULATOR.fields_by_name['nearest_iou_similarity'].containing_oneof = _REGIONSIMILARITYCALCULATOR.oneofs_by_name['region_similarity']
_REGIONSIMILARITYCALCULATOR.oneofs_by_name['region_similarity'].fields.append(
  _REGIONSIMILARITYCALCULATOR.fields_by_name['distance_similarity'])
_REGIONSIMILARITYCALCULATOR.fields_by_name['distance_similarity'].containing_oneof = _REGIONSIMILARITYCALCULATOR.oneofs_by_name['region_similarity']
DESCRIPTOR.message_types_by_name['RegionSimilarityCalculator'] = _REGIONSIMILARITYCALCULATOR
DESCRIPTOR.message_types_by_name['RotateIouSimilarity'] = _ROTATEIOUSIMILARITY
DESCRIPTOR.message_types_by_name['NearestIouSimilarity'] = _NEARESTIOUSIMILARITY
DESCRIPTOR.message_types_by_name['DistanceSimilarity'] = _DISTANCESIMILARITY

RegionSimilarityCalculator = _reflection.GeneratedProtocolMessageType('RegionSimilarityCalculator', (_message.Message,), dict(
  DESCRIPTOR = _REGIONSIMILARITYCALCULATOR,
  __module__ = 'prystine_detection.prystine.protos.similarity_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.RegionSimilarityCalculator)
  ))
_sym_db.RegisterMessage(RegionSimilarityCalculator)

RotateIouSimilarity = _reflection.GeneratedProtocolMessageType('RotateIouSimilarity', (_message.Message,), dict(
  DESCRIPTOR = _ROTATEIOUSIMILARITY,
  __module__ = 'prystine_detection.prystine.protos.similarity_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.RotateIouSimilarity)
  ))
_sym_db.RegisterMessage(RotateIouSimilarity)

NearestIouSimilarity = _reflection.GeneratedProtocolMessageType('NearestIouSimilarity', (_message.Message,), dict(
  DESCRIPTOR = _NEARESTIOUSIMILARITY,
  __module__ = 'prystine_detection.prystine.protos.similarity_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.NearestIouSimilarity)
  ))
_sym_db.RegisterMessage(NearestIouSimilarity)

DistanceSimilarity = _reflection.GeneratedProtocolMessageType('DistanceSimilarity', (_message.Message,), dict(
  DESCRIPTOR = _DISTANCESIMILARITY,
  __module__ = 'prystine_detection.prystine.protos.similarity_pb2'
  # @@protoc_insertion_point(class_scope:prystine_detection.prystine.protos.DistanceSimilarity)
  ))
_sym_db.RegisterMessage(DistanceSimilarity)


# @@protoc_insertion_point(module_scope)
